steps:
  # Instala las dependencias
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']

  # Ejecuta npm start (que ejecuta build y luego arranca app.js)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run','build']

timeout: '900s'  # Opcional, para builds largos
